### ISSUE TITLE
E/SpeechRecognizer(22424): no selected voice recognition service

### ISSUE THREAD

**Issue by daothan1211** [jaumard/flutter_speech_recognition#3]
I've used library futter_speech to record my voice. And I have faced a problem that cannot use it.
And it only happens on Android.
`E/SpeechRecognizer(22424): no selected voice recognition service`
Can anyone give me some help, please?
Thanks a lot.

**Comment by daothan1211** [comment]
I found out the solution, that needs to install google assistant, that I accidentally removed it before.

**Comment by sachin2376** [comment]
Hi @daothan1211 ,
Can you please share what solution have you found ?
how did you solve this ?
