### ISSUE TITLE
example is broken with macos 

### ISSUE THREAD

**Issue by ariagecheney** [jaumard/flutter_speech_recognition#7]
The [example](https://github.com/jaumard/flutter_speech_recognition/blob/master/example/lib/main.dart) 
reports  one bug :Exception: Error running pod install; 
 it works well for android ;
and then  i run " flutter run -d macos";   mbp 2019 ;catalina 10.15.4 ; 
see below :
Launching lib/main.dart on macOS desktop in debug mode...
Running pod install...                                              0.9s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_speech
      - FlutterMacOS
      - sign_in_with_apple

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral/.symlinks/flutter/darwin-x64`
    -> Fetching podspec for `flutter_speech` from
    `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`
    -> Fetching podspec for `sign_in_with_apple` from
    `Flutter/ephemeral/.symlinks/plugins/sign_in_with_apple/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
      perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_speech":
      In Podfile:
        flutter_speech (from `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`)

    Specs satisfying the `flutter_speech (from
    `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`)` dependency were found, but they
    required a higher minimum deployment target.

    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:328:in `raise_error_unless_state'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:310:in `block in unwind_for_conflict'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:308:in `tap'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:308:in `unwind_for_conflict'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:684:in `attempt_to_activate'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:254:in `process_topmost_state'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:182:in `resolve'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb
    :43:in `resolve'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb
    :94:in `resolve'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/a
    nalyzer.rb:1065:in `block in resolve_dependencies'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interf
    ace.rb:64:in `section'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/a
    nalyzer.rb:1063:in `resolve_dependencies'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/a
    nalyzer.rb:124:in `analyze'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.r
    b:410:in `analyze'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.r
    b:235:in `block in resolve_dependencies'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interf
    ace.rb:64:in `section'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.r
    b:234:in `resolve_dependencies'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.r
    b:156:in `install!'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/ins
    tall.rb:52:in `run'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:
    52:in `run'
    /Users/chy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    /Users/chy/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
    /Users/chy/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

Exception: Error running pod install
-----------------------------------------------------------------------------------
![flutter_speech_2](https://user-images.githubusercontent.com/35078844/85538701-b8f1a980-b647-11ea-9fd3-c9fab92e33cb.png)
![flutter_speech1](https://user-images.githubusercontent.com/35078844/85538717-bbec9a00-b647-11ea-9376-4394caf59935.png)

**Comment by jaumard** [comment]
Please try again with 2.0.0 should be good now

**Comment by rlfolden** [comment]
I just tried a macos build of the example main.dart file, and get the same error.

Launching lib/main.dart on macOS in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `flutter_speech` from `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_speech":
      In Podfile:
        flutter_speech (from `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`)

    Specs satisfying the `flutter_speech (from `Flutter/ephemeral/.symlinks/plugins/flutter_speech/macos`)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
